name: lit_starfield
description: A Flutter plugin for rendering an animated and customizable starfield on a dark background.
version: 0.1.2
homepage: https://github.com/litlifesoftware/lit_starfield

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
